import { Schema,model } from "mongoose";
import {SystemRoles}from '../../src/utils/SystemRoles.js'
import pkg from'bcrypt'
const UserSchema = new Schema({
    UserName:{
        type:String,
        required:true,
        lowercase:true,
        unique:true,
    },
    Email:{
        type:String,
        unique:true,
        required:true,
        lowercase:true,
    },
    Password:{
        type:String,
        required:true,
    },
    ConfirmPassword:{
        type:String,
        required:true,
    },
    ProfilePic:{
        public_id:String,
        secure_url:String
    },
    Gender:{
        type:String,
        enum:[SystemRoles.Female,SystemRoles.Male,SystemRoles.Not_Specified],
        default:SystemRoles.Not_Specified,
    },
    isConfirmed:{
        type:Boolean,
        required:true,
        default:false
    },
    Address:[{
        type:String,
        required:true
        },
        ],
    isDeleted:{
        type:Boolean,
        default:false,
    },
    token:{
        type:String,
    },
    Code:{
        type:String,
        default:null
    },
    role:{
        type:String,
        enum:[SystemRoles.User,SystemRoles.Admin,SystemRoles.Super],
        default:SystemRoles.User,
    },
    ChangePassAt:{
        type:Date
    },
    QuizMarks:[{
            QuizId:{
                type:Schema.Types.ObjectId,
                ref:"Quiz"
            },
            QuizName:String,
            Mark:Number,

    }],
    status:{
        type:String,
        default:'Offline',
        enum:['Online','Offline']
    },
    Age:Number,
    FirstName:String,
    LastName:String,
    professionalheadline:String,
},{timestamps:true}
)
UserSchema.pre("save",function(next,hash){
    this.Password=pkg.hashSync(this.Password,+process.env.SALT_ROUNDS)
    this.ConfirmPassword=this.Password
    next()
})
export const UserModel=model('User',UserSchema)